-- 숫자 함수
--ROUND - 반올림 (매개변수가 하나라면 반올림 ,
--두개라면 두번째가 소수점 자리를 의미, 음수라면 소수점의 왼쪽 자리수만큼)
SELECT ROUND(45.523,2),ROUND(45.523),ROUND(145.523 , -2) FROM DUAL;
--TRUNC()- 절삭
SELECT TRUNC(45.523,2),TRUNC(45.523),TRUNC(45.523,-1) FROM DUAL;
--CEIL() 올림 , FLOOR() 내림
SELECT CEIL(3.14), FLOOR(3.14) FROM DUAL;
--MOD() - 나머지
SELECT MOD(5,3) AS 나머지, TRUNC(5/3) AS 몫 FROM DUAL;
--------------------------------------------------

--날짜함수
SELECT SYSDATE FROM DUAL; --년/월/일
SELECT SYSTIMESTAMP FROM DUAL; -- 시분초 밀리세컨을 포함한 상세한 시간타입

--날짜의연산 = 기준이 일수
SELECT SYSDATE + 10 FROM DUAL; -- +10일
SELECT SYSDATE - 10 FROM DUAL; -- -10일
SELECT SYSDATE-HIRE_DATE FROM EMPLOYEES; --일수
SELECT (SYSDATE-HIRE_DATE)/7 AS WEEK FROM EMPLOYEES;
SELECT (SYSDATE-HIRE_DATE)/365 AS YEAR FROM EMPLOYEES;
SELECT TRUNC((SYSDATE-HIRE_DATE)/365) * 12 AS MONTH FROM EMPLOYEES;

--날짜의 반올림, 절삭
SELECT ROUND(SYSDATE) FROM DUAL; -- 오늘의 날짜를 시간기준으로 반올림
SELECT ROUND(SYSDATE,'DAY') FROM DUAL; -- 반올림한 주의 일요일로
SELECT ROUND(SYSDATE,'MONTH') FROM DUAL; -- 월 기준으로 반올림
SELECT ROUND(SYSDATE,'YEAR') FROM DUAL; -- 년을 기준으로 반올림

SELECT TRUNC(SYSDATE) FROM DUAL; -- 오늘을 반환
SELECT TRUNC(SYSDATE,'DAY') FROM DUAL; -- 해당주의 일요일로
SELECT TRUNC(SYSDATE,'MONTH') FROM DUAL; -- 해당 월의 1일로
SELECT TRUNC(SYSDATE,'YEAR') FROM DUAL; -- 해당 년의 1월1일로

