SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

-- 1
SELECT * FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.department_id; -- 106
SELECT * FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID; -- 107
SELECT * FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID; -- 122
SELECT * FROM EMPLOYEES E FULL JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID; -- 123

-- 2
SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME , E.DEPARTMENT_ID
FROM EMPLOYEES E JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
WHERE EMPLOYEE_ID = 200;

-- 3
SELECT * FROM JOBS;
SELECT E.FIRST_NAME,
       J.JOB_ID,
       J.JOB_TITLE
FROM EMPLOYEES E JOIN JOBS J ON E.JOB_ID = J.JOB_ID
ORDER BY FIRST_NAME;

--쌤 풀이
SELECT E.FIRST_NAME,
       J.JOB_TITLE
FROM EMPLOYEES E JOIN JOBS J USING (JOB_ID)
ORDER BY FIRST_NAME;

--4

SELECT * FROM JOBS J LEFT JOIN JOB_HISTORY J2 ON J.JOB_ID = J2.JOB_ID; 

--5
SELECT D.DEPARTMENT_NAME
FROM EMPLOYEES E FULL OUTER JOIN  DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE FIRST_NAME||' '||LAST_NAME = 'Steven King' ;

--6
SELECT * FROM EMPLOYEES; -- 107
SELECT * FROM DEPARTMENTS; --27

SELECT * FROM EMPLOYEES CROSS JOIN DEPARTMENTS; -- 2889개

--7
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;

SELECT E.EMPLOYEE_ID 사원번호, E.FIRST_NAME 이름, E.SALARY 급여,D.DEPARTMENT_NAME 부서명, L.STREET_ADDRESS 근무지 
FROM DEPARTMENTS D LEFT OUTER JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
                              JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE E.JOB_ID = 'SA_MAN'
ORDER BY E.EMPLOYEE_ID;

-- 쌤 풀이
SELECT E.FIRST_NAME,
       E.SALARY,
       D.DEPARTMENT_NAME,
       L.STREET_ADDRESS
FROM EMPLOYEES E 
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID
WHERE JOB_ID = 'SA_MAN';


--8
SELECT * FROM JOBS;
SELECT *
FROM EMPLOYEES E FULL OUTER JOIN JOBS J ON E.JOB_ID = J.JOB_ID
WHERE J.JOB_TITLE IN('Stock Manager','Stock Clerk');

--9
SELECT * FROM DEPARTMENTS; 
SELECT * FROM EMPLOYEES;

SELECT DEPARTMENT_NAME
FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE EMPLOYEE_ID IS NULL;

-- 쌤풀이
SELECT DEPARTMENT_NAME
FROM DEPARTMENTS D LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE EMPLOYEE_ID IS NULL;

--10

SELECT E1 .FIRST_NAME AS 사원이름 ,E2.FIRST_NAME 매니저이름
FROM EMPLOYEES E1 LEFT OUTER JOIN EMPLOYEES E2 ON E1.EMPLOYEE_ID = E2.MANAGER_ID;


--11
SELECT E1.FIRST_NAME AS 사원,E1.MANAGER_ID AS 사원의매니저, E2.FIRST_NAME 매니저이름 , E2.SALARY 매니저급여
FROM EMPLOYEES E1 LEFT OUTER JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID
WHERE E1.MANAGER_ID IS NOT NULL AND E2.FIRST_NAME IS NOT NULL
ORDER BY E2.SALARY DESC;

SELECT E1.FIRST_NAME AS 사원명,
       E1.SALARY AS 사원급여,
       E2.EMPLOYEE_ID AS 매니저아이디,
       E2.FIRST_NAME AS 매니저명,
       E2.SALARY AS 매니저급여
FROM EMPLOYEES E1 LEFT JOIN EMPLOYEES E2 ON E1.MANAGER_ID = E2.EMPLOYEE_ID
WHERE E1.MANAGER_ID IS NOT NULL
ORDER BY E1.SALARY DESC;

